### ISSUE TITLE
Display mouve coordinates

### ISSUE THREAD

**Issue by ebocher** [orbisgis/mapuce.orbisgis.org#1]
Add a function or a plugin to display mouse coordinates.

**Comment by ebocher** [comment]
@gpetit 
Required ?

**Comment by gpetit** [comment]
Yes sure. In most of GIS software, this behaviour is available by default ;-)

If possible, it would be great if we were able to select & copy the coordinates.

And also, if would be interesting if we were able to enter coordinates in this "text area", in order to change to center of the map

**Comment by ebocher** [comment]
Done with new nice features
