### ISSUE TITLE
Erroneous position of Quimper

### ISSUE THREAD

**Issue by VakankGrang** [orbisgis/mapuce.orbisgis.org#3]
It seems to me that Quimperlé has been mistaken with Quimper. 

Best regards,
Robert

**Comment by gpetit** [comment]
Good catch @VakankGrang

It seems that the "Unité Urbaine" of Quimper is based on the cities of "Quimperlé and Tréméven". 
So yes there is an error ... made by LIENSs.

We do not plan to fix this.

@ebocher

**Comment by ebocher** [comment]
Oh yes in the database we have "Import commune Quimperlé de la zone de Quimper. Quimper 29233 "
